- name: ensure nginx ssl folder
  file:
    path: "{{ nginx_filesystem_ssl }}"
    state: directory

- name: ensure dh params file
  openssl_dhparam:
    path: "{{ nginx_filesystem_ssl }}/{{ nginx_config_cert_name }}-dhparam.pem"

- name: ensure openssl private key
  openssl_privatekey:
    path: "{{ nginx_filesystem_ssl }}/{{ nginx_config_cert_name }}.key"
    size: 4096

- name: ensure csr
  openssl_csr:
    path: "{{ nginx_filesystem_ssl }}/{{ nginx_config_cert_name }}.csr"
    privatekey_path: "{{ nginx_filesystem_ssl }}/{{ nginx_config_cert_name }}.key"
    common_name: "{{ nginx_config_cert_common_name }}"
    email_address: "{{ nginx_config_cert_email }}"

- name: ensure signed openssl cert
  openssl_certificate:
    path: "{{ nginx_filesystem_ssl }}/{{ nginx_config_cert_name }}.crt"
    privatekey_path: "{{ nginx_filesystem_ssl }}/{{ nginx_config_cert_name }}.key"
    csr_path: "{{ nginx_filesystem_ssl }}/{{ nginx_config_cert_name }}.csr"
    provider: selfsigned